M48
; DRILL file {KiCad (6.0.2-0)} date Sunday, 10 April 2022 at 10:20:31
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-10T10:20:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.0354Y-2.5787
X4.0354Y-3.8386
X5.5906Y-2.5787
X5.5906Y-3.8386
T0
M30
